server:
  port: 8088

management:
#  server:
#    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: k8s-srv-user
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    kubernetes:
      loadbalancer:
        mode: service
      discovery:
        enabled: true
      client:
        namespace: hup-ns